# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Description of what the lane does"
  # lane :custom_lane do
  #   # add actions here: https://docs.fastlane.tools/actions
  # end
  desc "The Road to Mediocre Life"
  lane :mediocre do |options|
    branch=options[:branch]
    target_version=options[:version]
    message=options[:message]
    git_pull
    ensure_git_branch
    cocoapods(
      podfile: "Podfile",
      repo_update: true
    )
    git_add
    git_commit(message: "#{message}")
    add_git_tag(tag: target_version)
    push_to_git_remote
    la_city_cover
  end
end
